name: seatsio
description: Seatsio SDK for Flutter.
repository: https://github.com/SongJiaqiang/seatsio-flutter
version: 0.4.0

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.9.0
  built_collection: ^5.1.1
  built_value: ^8.9.5
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner: ^2.4.15
  built_value_generator: ^8.9.5
