name: seatsio
description: Seatsio SDK for Flutter.
repository: https://github.com/SongJiaqiang/seatsio-flutter
version: 0.3.4

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.17.0"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.8.1
  built_collection: ^5.1.1
  built_value: ^8.7.0
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  built_value_generator: ^8.7.0

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
